package def_test

import (
	. "testing"

	"github.com/pjherring/mysql-gen/def"
	"github.com/stretchr/testify/assert"
)

func TestParseTableFromFile(t *T) {

	json := []byte(`
    {
        "name": "users",
        "fields": {
            "user_id": "int64",
            "name": "string",
            "create_date": "mysql.NullTime",
            "update_date": "mysql.NullTime",
            "telephone": "string",
            "group_id": "int64"
        },
		"primary_keys": ["user_id", "group_id"],
		"auto_generated": ["user_id"],
        "queries": {
            "findById": "SELECT * FROM users WHERE user_id = ?",
            "findManyByGroupId": "SELECT * FROM users WHERE group_id = ? LIMIT ? OFFSET ?",
			"getManyUserIdsByName": "SELECT user_id FROM users WHERE name = ?"
        }
    }
	`)

	table, err := def.ParseTable(json)

	assert.Nil(t, err)

	assert.Equal(t, "User", table.Name)
	assert.Equal(t, "users", table.Raw)
	assert.Equal(t, 6, len(table.Fields))

	assert.Equal(t, "UserId", table.Field("user_id").Name)
	assert.Equal(t, "int64", table.Field("user_id").Type)
	assert.Equal(t, "user_id", table.Field("user_id").Raw)
	assert.True(t, table.Field("user_id").IsAutoGenerated)

	assert.Equal(t, "Name", table.Field("name").Name)
	assert.Equal(t, "string", table.Field("name").Type)
	assert.Equal(t, "name", table.Field("name").Raw)
	assert.False(t, table.Field("name").IsAutoGenerated)

	assert.Equal(t, "CreateDate", table.Field("create_date").Name)
	assert.Equal(t, "mysql.NullTime", table.Field("create_date").Type)
	assert.Equal(t, "create_date", table.Field("create_date").Raw)

	assert.Equal(t, "UpdateDate", table.Field("update_date").Name)
	assert.Equal(t, "mysql.NullTime", table.Field("update_date").Type)
	assert.Equal(t, "update_date", table.Field("update_date").Raw)

	assert.Equal(t, "Telephone", table.Field("telephone").Name)
	assert.Equal(t, "string", table.Field("telephone").Type)
	assert.Equal(t, "telephone", table.Field("telephone").Raw)

	assert.Equal(t, "GroupId", table.Field("group_id").Name)
	assert.Equal(t, "int64", table.Field("group_id").Type)
	assert.Equal(t, "group_id", table.Field("group_id").Raw)

	assert.Equal(t, 2, len(table.PrimaryKeys))
	assert.Equal(t, "UserId", table.PrimaryKeys[0].Name)
	assert.Equal(t, "GroupId", table.PrimaryKeys[1].Name)

	assert.Equal(t, "FindById", table.Queries["findById"].Name)
	assert.False(t, table.Queries["findById"].IsMulti)
	assert.Equal(t, 1, len(table.Queries["findById"].Params))
	assert.Equal(t, 0, len(table.Queries["findById"].SelectFields))
	assert.Equal(t, "UserId", table.Queries["findById"].Params[0].Name)
	assert.Equal(t, "SELECT * FROM users WHERE user_id = ?", table.Queries["findById"].Sql)

	assert.Equal(t, "FindManyByGroupId", table.Queries["findManyByGroupId"].Name)
	assert.True(t, table.Queries["findManyByGroupId"].IsMulti)
	assert.Equal(t, 3, len(table.Queries["findManyByGroupId"].Params))
	assert.Equal(t, 0, len(table.Queries["findById"].SelectFields))
	assert.Equal(t, "GroupId", table.Queries["findManyByGroupId"].Params[0].Name)
	assert.Equal(t, "Limit", table.Queries["findManyByGroupId"].Params[1].Name)
	assert.Equal(t, "limit", table.Queries["findManyByGroupId"].Params[1].Arg)
	assert.Equal(t, "Offset", table.Queries["findManyByGroupId"].Params[2].Name)
	assert.Equal(t, "offset", table.Queries["findManyByGroupId"].Params[2].Arg)

	//"getManyUserIdsByName: "SELECT user_id FROM users WHERE name = ?"
	assert.Equal(t, "GetManyUserIdsByName", table.Queries["getManyUserIdsByName"].Name)
	assert.True(t, table.Queries["getManyUserIdsByName"].IsMulti)
	assert.Equal(t, 1, len(table.Queries["getManyUserIdsByName"].Params))
	assert.Equal(t, 1, len(table.Queries["getManyUserIdsByName"].SelectFields))
	assert.Equal(t, "UserId", table.Queries["getManyUserIdsByName"].SelectFields[0].Name)
	assert.Equal(t, "Name", table.Queries["getManyUserIdsByName"].Params[0].Name)

}
