package def

type Field struct {
	Arg             string
	Name            string
	Type            string
	Raw             string
	Order           int
	IsPrimaryKey    bool
	IsAutoGenerated bool
}

type Query struct {
	Name         string
	IsMulti      bool
	Params       Fields
	SelectFields Fields
	Sql          string
}

type Table struct {
	Name        string
	Raw         string
	Fields      Fields
	fieldMap    map[string]*Field
	Queries     map[string]Query
	PrimaryKeys Fields
}

func (t Table) Field(name string) *Field {
	return t.fieldMap[name]
}
