package {{.Raw}}

func (t *{{.Name}}) Store() error {
	if t.IsStored {
		return t.insert()
	}

	return t.update()
}

func (t *{{.Name}}) update() error {
    _, err := gen.GetDb().Exec(
        "UPDATE {{.Raw}} SET {{.NonPrimaryKeyColumnsPlaceholders}} WHERE {{.PrimaryKeyColumnPlaceholders}}",
        {{.NonPrimaryKeyNames}}, {{.PrimaryKeyNames}},
    )

    if err != nil {
        t.IsStored = true
    }

    return err
}

func (t *{{.Name}}) insert() error {
    r, err := gen.GetDb().Exec(
        "INSERT INTO {{.Raw}} ({{.NotAutoGeneratedColumns}}) VALUES ({{.Placeholders .NotAutoGeneratedColumnCnt}})",
        {{.NotAutoGeneratedNames}},
    )

    if err == nil {
        t.{{.AutoGeneratedName}} = r.LastInsertId()
        t.IsStored = true
    }

    return err
}
